import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { QueryProvider } from "@/lib/query-client";

import { Navbar } from "./components/navbar";
import "./globals.css";

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solvro Web Template",
  description: "Generated by create next app with solvro config",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body
          className={`${space_grotesk.variable} flex h-screen flex-col font-sans antialiased`}
        >
          <Navbar />
          <div className="h-full w-screen">{children}</div>
        </body>
      </QueryProvider>
    </html>
  );
}
