import type { Pluralized, RecordIntersection } from "@/types/helpers";
import type {
  DeclensionData,
  Declensions,
  DeclinableSimpleNoun,
} from "@/types/polish";

import { GrammaticalGender, Resource } from "./enums";

/** A dictionary of Polish language declensions of all resource names & other nouns, as well as their genders for use with determiners. */
export const SIMPLE_NOUN_DECLENSIONS = {
  [Resource.Departments]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "wydział",
      genitive: "wydziału",
      dative: "wydziałowi",
      accusative: "wydział",
      instrumental: "wydziałem",
      locative: "wydziale",
      vocative: "wydziale",
    },
    plural: {
      nominative: "wydziały",
      genitive: "wydziałów",
      dative: "wydziałom",
      accusative: "wydziały",
      instrumental: "wydziałami",
      locative: "wydziałach",
      vocative: "wydziały",
    },
  },
  [Resource.GuideArticles]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "artykuł",
      genitive: "artykułu",
      dative: "artykułowi",
      accusative: "artykuł",
      instrumental: "artykułem",
      locative: "artykule",
      vocative: "artykule",
    },
    plural: {
      nominative: "artykuły",
      genitive: "artykułów",
      dative: "artykułom",
      accusative: "artykuły",
      instrumental: "artykułami",
      locative: "artykułach",
      vocative: "artykuły",
    },
  },
  [Resource.GuideAuthors]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "autor",
      genitive: "autora",
      dative: "autorowi",
      accusative: "autora",
      instrumental: "autorem",
      locative: "autorze",
      vocative: "autorze",
    },
    plural: {
      nominative: "autorzy",
      genitive: "autorów",
      dative: "autorom",
      accusative: "autorów",
      instrumental: "autorami",
      locative: "autorach",
      vocative: "autorzy",
    },
  },
  [Resource.StudentOrganizations]: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "organizacja studencka",
      genitive: "organizacji studenckiej",
      dative: "organizacji studenckiej",
      accusative: "organizację studencką",
      instrumental: "organizacją studencką",
      locative: "organizacji studenckiej",
      vocative: "organizacjo studencka",
    },
    plural: {
      nominative: "organizacje studenckie",
      genitive: "organizacji studenckich",
      dative: "organizacjom studenckim",
      accusative: "organizacje studenckie",
      instrumental: "organizacjami studenckimi",
      locative: "organizacjach studenckich",
      vocative: "organizacje studenckie",
    },
  },
  [Resource.StudentOrganizationLinks]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "link",
      genitive: "linku",
      dative: "linkowi",
      accusative: "link",
      instrumental: "linkiem",
      locative: "linku",
      vocative: "linku",
    },
    plural: {
      nominative: "linki",
      genitive: "linków",
      dative: "linkom",
      accusative: "linki",
      instrumental: "linkami",
      locative: "linkach",
      vocative: "linki",
    },
  },
  [Resource.StudentOrganizationTags]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "tag",
      genitive: "tagu",
      dative: "tagowi",
      accusative: "tag",
      instrumental: "tagiem",
      locative: "tagu",
      vocative: "tagu",
    },
    plural: {
      nominative: "tagi",
      genitive: "tagów",
      dative: "tagom",
      accusative: "tagi",
      instrumental: "tagami",
      locative: "tagach",
      vocative: "tagi",
    },
  },
  [Resource.CalendarEvents]: {
    gender: GrammaticalGender.Neuter,
    singular: {
      nominative: "wydarzenie kalendarzowe",
      genitive: "wydarzenia kalendarzowego",
      dative: "wydarzeniu kalendarzowemu",
      accusative: "wydarzenie kalendarzowe",
      instrumental: "wydarzeniem kalendarzowym",
      locative: "wydarzeniu kalendarzowemu",
      vocative: "wydarzenie kalendarzowe",
    },
    plural: {
      nominative: "wydarzenia kalendarzowe",
      genitive: "wydarzeń kalendarzowych",
      dative: "wydarzeniom kalendarzowym",
      accusative: "wydarzenia kalendarzowe",
      instrumental: "wydarzeniami kalendarzowymi",
      locative: "wydarzeniach kalendarzowych",
      vocative: "wydarzenia kalendarzowe",
    },
  },
  [Resource.Banners]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "baner",
      genitive: "baneru",
      dative: "banerowi",
      accusative: "baner",
      instrumental: "banerem",
      locative: "banerze",
      vocative: "banerze",
    },
    plural: {
      nominative: "banery",
      genitive: "banerów",
      dative: "banerom",
      accusative: "banery",
      instrumental: "banerami",
      locative: "banerach",
      vocative: "banery",
    },
  },
  image: {
    gender: GrammaticalGender.Neuter,
    singular: {
      nominative: "zdjęcie",
      genitive: "zdjęcia",
      dative: "zdjęciu",
      accusative: "zdjęcie",
      instrumental: "zdjęciem",
      locative: "zdjęciu",
      vocative: "zdjęcie",
    },
    plural: {
      nominative: "zdjęcia",
      genitive: "zdjęć",
      dative: "zdjęciom",
      accusative: "zdjęcia",
      instrumental: "zdjęciami",
      locative: "zdjęciach",
      vocative: "zdjęcia",
    },
  },
  name: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "nazwa",
      genitive: "nazwy",
      dative: "nazwie",
      accusative: "nazwę",
      instrumental: "nazwą",
      locative: "nazwie",
      vocative: "nazwa",
    },
    plural: {
      nominative: "nazwy",
      genitive: "nazw",
      dative: "nazwom",
      accusative: "nazwy",
      instrumental: "nazwami",
      locative: "nazwach",
      vocative: "nazwy",
    },
  },
  title: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "tytuł",
      genitive: "tytułu",
      dative: "tytułowi",
      accusative: "tytuł",
      instrumental: "tytułem",
      locative: "tytule",
      vocative: "tytule",
    },
    plural: {
      nominative: "tytuły",
      genitive: "tytułów",
      dative: "tytułom",
      accusative: "tytuły",
      instrumental: "tytułami",
      locative: "tytułach",
      vocative: "tytuły",
    },
  },
  description: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "opis",
      genitive: "opisu",
      dative: "opisowi",
      accusative: "opis",
      instrumental: "opisem",
      locative: "opisie",
      vocative: "opisie",
    },
    plural: {
      nominative: "opisy",
      genitive: "opisów",
      dative: "opisy",
      accusative: "opisy",
      instrumental: "opisami",
      locative: "opisach",
      vocative: "opisy",
    },
  },
  shortDescription: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "krótki opis",
      genitive: "krótkiego opisu",
      dative: "krótkiemu opisowi",
      accusative: "krótki opis",
      instrumental: "krótkim opisem",
      locative: "krótkim opisie",
      vocative: "krótkim opisie",
    },
    plural: {
      nominative: "krótkie opisy",
      genitive: "krótkich opisów",
      dative: "krótkim opisom",
      accusative: "krótkie opisy",
      instrumental: "krótkimi opisami",
      locative: "krótkich opisach",
      vocative: "krótkie opisy",
    },
  },
  id: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "identyfikator",
      genitive: "identyfikatora",
      dative: "identyfikatorowi",
      accusative: "identyfikator",
      instrumental: "identyfikatorem",
      locative: "identyfikatorze",
      vocative: "identyfikatorze",
    },
    plural: {
      nominative: "identyfikatory",
      genitive: "identyfikatorów",
      dative: "identyfikatorom",
      accusative: "identyfikatory",
      instrumental: "identyfikatorami",
      locative: "identyfikatorach",
      vocative: "identyfikatory",
    },
  },
  date: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "data",
      genitive: "daty",
      dative: "dacie",
      accusative: "datę",
      instrumental: "datą",
      locative: "dacie",
      vocative: "dato",
    },
    plural: {
      nominative: "daty",
      genitive: "dat",
      dative: "datom",
      accusative: "daty",
      instrumental: "datami",
      locative: "datach",
      vocative: "daty",
    },
  },
} satisfies RecordIntersection<
  Resource,
  string,
  Pluralized<Declensions> & DeclensionData
>;

/** Noun phrase mappings that inflect like their base noun with genitive transformations (e.g. 'data' → 'data utworzenia'). */
export const NOUN_PHRASE_TRANSFORMATIONS = {
  createdAt: {
    base: "date",
    transform: (base) => `${base} utworzenia`,
  },
  updatedAt: {
    base: "date",
    transform: (base) => `${base} aktualizacji`,
  },
} satisfies Record<
  string,
  { base: DeclinableSimpleNoun; transform: (base: string) => string }
>;

/** A static dictionary of declensions for determiners in the Polish language. */
export const DETERMINER_DECLENSIONS = {
  this: {
    [GrammaticalGender.Masculine]: {
      singular: {
        nominative: "ten",
        genitive: "tego",
        dative: "temu",
        accusative: "ten",
        instrumental: "tym",
        locative: "tym",
        vocative: "ten",
      },
      plural: {
        nominative: "ci",
        genitive: "tych",
        dative: "tym",
        accusative: "tych",
        instrumental: "tymi",
        locative: "tych",
        vocative: "ci",
      },
    },
    [GrammaticalGender.Feminine]: {
      singular: {
        nominative: "ta",
        genitive: "tej",
        dative: "tej",
        accusative: "tę",
        instrumental: "tą",
        locative: "tej",
        vocative: "ta",
      },
      plural: {
        nominative: "te",
        genitive: "tych",
        dative: "tym",
        accusative: "te",
        instrumental: "tymi",
        locative: "tych",
        vocative: "te",
      },
    },
    [GrammaticalGender.Neuter]: {
      singular: {
        nominative: "to",
        genitive: "tego",
        dative: "temu",
        accusative: "to",
        instrumental: "tym",
        locative: "tym",
        vocative: "to",
      },
      plural: {
        nominative: "te",
        genitive: "tych",
        dative: "tym",
        accusative: "te",
        instrumental: "tymi",
        locative: "tych",
        vocative: "te",
      },
    },
  },
  new: {
    [GrammaticalGender.Masculine]: {
      singular: {
        nominative: "nowy",
        genitive: "nowego",
        dative: "nowemu",
        accusative: "nowy",
        instrumental: "nowym",
        locative: "nowym",
        vocative: "nowy",
      },
      plural: {
        nominative: "nowi",
        genitive: "nowych",
        dative: "nowym",
        accusative: "nowych",
        instrumental: "nowymi",
        locative: "nowych",
        vocative: "nowi",
      },
    },
    [GrammaticalGender.Feminine]: {
      singular: {
        nominative: "nowa",
        genitive: "nowej",
        dative: "nowej",
        accusative: "nową",
        instrumental: "nową",
        locative: "nowej",
        vocative: "nowa",
      },
      plural: {
        nominative: "nowe",
        genitive: "nowych",
        dative: "nowym",
        accusative: "nowe",
        instrumental: "nowymi",
        locative: "nowych",
        vocative: "nowe",
      },
    },
    [GrammaticalGender.Neuter]: {
      singular: {
        nominative: "nowe",
        genitive: "nowego",
        dative: "nowemu",
        accusative: "nowe",
        instrumental: "nowym",
        locative: "nowym",
        vocative: "nowe",
      },
      plural: {
        nominative: "nowe",
        genitive: "nowych",
        dative: "nowym",
        accusative: "nowe",
        instrumental: "nowymi",
        locative: "nowych",
        vocative: "nowe",
      },
    },
  },
  existing: {
    [GrammaticalGender.Masculine]: {
      singular: {
        nominative: "istniejący",
        genitive: "istniejącego",
        dative: "istniejącemu",
        accusative: "istniejący",
        instrumental: "istniejącym",
        locative: "istniejącym",
        vocative: "istniejący",
      },
      plural: {
        nominative: "istniejący",
        genitive: "istniejących",
        dative: "istniejącym",
        accusative: "istniejących",
        instrumental: "istniejącymi",
        locative: "istniejących",
        vocative: "istniejący",
      },
    },
    [GrammaticalGender.Feminine]: {
      singular: {
        nominative: "istniejąca",
        genitive: "istniejącej",
        dative: "istniejącej",
        accusative: "istniejącą",
        instrumental: "istniejącą",
        locative: "istniejącej",
        vocative: "istniejąca",
      },
      plural: {
        nominative: "istniejące",
        genitive: "istniejących",
        dative: "istniejącym",
        accusative: "istniejące",
        instrumental: "istniejącymi",
        locative: "istniejących",
        vocative: "istniejące",
      },
    },
    [GrammaticalGender.Neuter]: {
      singular: {
        nominative: "istniejące",
        genitive: "istniejącego",
        dative: "istniejącemu",
        accusative: "istniejące",
        instrumental: "istniejącym",
        locative: "istniejącym",
        vocative: "istniejące",
      },
      plural: {
        nominative: "istniejące",
        genitive: "istniejących",
        dative: "istniejącym",
        accusative: "istniejące",
        instrumental: "istniejącymi",
        locative: "istniejących",
        vocative: "istniejące",
      },
    },
  },
} satisfies Record<string, Record<GrammaticalGender, Pluralized<Declensions>>>;
