import { quoteText } from "@/lib/helpers/transformations";
import type { Pluralized, RecordIntersection } from "@/types/helpers";
import type {
  DeclensionData,
  Declensions,
  DeclinableSimpleNoun,
} from "@/types/polish";

import { GrammaticalGender, Resource } from "./enums";

const QUOTED_ABOUT_US = quoteText("o nas");

const REUSABLE_DECLENSIONS = {
  link: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "link",
      genitive: "linku",
      dative: "linkowi",
      accusative: "link",
      instrumental: "linkiem",
      locative: "linku",
      vocative: "linku",
    },
    plural: {
      nominative: "linki",
      genitive: "linków",
      dative: "linkom",
      accusative: "linki",
      instrumental: "linkami",
      locative: "linkach",
      vocative: "linki",
    },
  },
  version: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "wersja",
      genitive: "wersji",
      dative: "wersji",
      accusative: "wersję",
      instrumental: "wersją",
      locative: "wersji",
      vocative: "wersjo",
    },
    plural: {
      nominative: "wersje",
      genitive: "wersji",
      dative: "wersjom",
      accusative: "wersje",
      instrumental: "wersjami",
      locative: "wersjach",
      vocative: "wersje",
    },
  },
  shortDescription: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "krótki opis",
      genitive: "krótkiego opisu",
      dative: "krótkiemu opisowi",
      accusative: "krótki opis",
      instrumental: "krótkim opisem",
      locative: "krótkim opisie",
      vocative: "krótkim opisie",
    },
    plural: {
      nominative: "krótkie opisy",
      genitive: "krótkich opisów",
      dative: "krótkim opisom",
      accusative: "krótkie opisy",
      instrumental: "krótkimi opisami",
      locative: "krótkich opisach",
      vocative: "krótkie opisy",
    },
  },
} satisfies Record<string, Pluralized<Declensions> & DeclensionData>;

/** A dictionary of Polish language declensions of all resource names & other nouns, as well as their genders for use with determiners. */
export const SIMPLE_NOUN_DECLENSIONS = {
  [Resource.Banners]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "baner",
      genitive: "baneru",
      dative: "banerowi",
      accusative: "baner",
      instrumental: "banerem",
      locative: "banerze",
      vocative: "banerze",
    },
    plural: {
      nominative: "banery",
      genitive: "banerów",
      dative: "banerom",
      accusative: "banery",
      instrumental: "banerami",
      locative: "banerach",
      vocative: "banery",
    },
  },
  [Resource.CalendarEvents]: {
    gender: GrammaticalGender.Neuter,
    singular: {
      nominative: "wydarzenie kalendarzowe",
      genitive: "wydarzenia kalendarzowego",
      dative: "wydarzeniu kalendarzowemu",
      accusative: "wydarzenie kalendarzowe",
      instrumental: "wydarzeniem kalendarzowym",
      locative: "wydarzeniu kalendarzowemu",
      vocative: "wydarzenie kalendarzowe",
    },
    plural: {
      nominative: "wydarzenia kalendarzowe",
      genitive: "wydarzeń kalendarzowych",
      dative: "wydarzeniom kalendarzowym",
      accusative: "wydarzenia kalendarzowe",
      instrumental: "wydarzeniami kalendarzowymi",
      locative: "wydarzeniach kalendarzowych",
      vocative: "wydarzenia kalendarzowe",
    },
  },
  [Resource.Changes]: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "zmiana",
      genitive: "zmiany",
      dative: "zmianie",
      accusative: "zmianę",
      instrumental: "zmianą",
      locative: "zmianie",
      vocative: "zmiano",
    },
    plural: {
      nominative: "zmiany",
      genitive: "zmian",
      dative: "zmianom",
      accusative: "zmiany",
      instrumental: "zmianami",
      locative: "zmianach",
      vocative: "zmiany",
    },
  },
  [Resource.Contributors]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "kontrybutor",
      genitive: "kontrybutora",
      dative: "kontrybutorowi",
      accusative: "kontrybutora",
      instrumental: "kontrybutorem",
      locative: "kontrybutorze",
      vocative: "kontrybutorze",
    },
    plural: {
      nominative: "kontrybutorzy",
      genitive: "kontrybutorów",
      dative: "kontrybutorom",
      accusative: "kontrybutorów",
      instrumental: "kontrybutorami",
      locative: "kontrybutorach",
      vocative: "kontrybutorzy",
    },
  },
  [Resource.ContributorSocialLinks]: REUSABLE_DECLENSIONS.link,
  [Resource.Departments]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "wydział",
      genitive: "wydziału",
      dative: "wydziałowi",
      accusative: "wydział",
      instrumental: "wydziałem",
      locative: "wydziale",
      vocative: "wydziale",
    },
    plural: {
      nominative: "wydziały",
      genitive: "wydziałów",
      dative: "wydziałom",
      accusative: "wydziały",
      instrumental: "wydziałami",
      locative: "wydziałach",
      vocative: "wydziały",
    },
  },
  [Resource.DepartmentLinks]: REUSABLE_DECLENSIONS.link,
  [Resource.GuideArticles]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "artykuł",
      genitive: "artykułu",
      dative: "artykułowi",
      accusative: "artykuł",
      instrumental: "artykułem",
      locative: "artykule",
      vocative: "artykule",
    },
    plural: {
      nominative: "artykuły",
      genitive: "artykułów",
      dative: "artykułom",
      accusative: "artykuły",
      instrumental: "artykułami",
      locative: "artykułach",
      vocative: "artykuły",
    },
  },
  [Resource.GuideAuthors]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "autor",
      genitive: "autora",
      dative: "autorowi",
      accusative: "autora",
      instrumental: "autorem",
      locative: "autorze",
      vocative: "autorze",
    },
    plural: {
      nominative: "autorzy",
      genitive: "autorów",
      dative: "autorom",
      accusative: "autorów",
      instrumental: "autorami",
      locative: "autorach",
      vocative: "autorzy",
    },
  },
  [Resource.GuideQuestions]: {
    gender: GrammaticalGender.Neuter,
    singular: {
      nominative: "pytanie",
      genitive: "pytania",
      dative: "pytaniu",
      accusative: "pytanie",
      instrumental: "pytaniem",
      locative: "pytaniu",
      vocative: "pytanie",
    },
    plural: {
      nominative: "pytania",
      genitive: "pytań",
      dative: "pytaniom",
      accusative: "pytania",
      instrumental: "pytaniami",
      locative: "pytaniach",
      vocative: "pytania",
    },
  },
  [Resource.Roles]: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "rola",
      genitive: "roli",
      dative: "roli",
      accusative: "rolę",
      instrumental: "rolą",
      locative: "roli",
      vocative: "rolo",
    },
    plural: {
      nominative: "role",
      genitive: "ról",
      dative: "rolom",
      accusative: "role",
      instrumental: "rolami",
      locative: "rolach",
      vocative: "role",
    },
  },
  [Resource.StudentOrganizations]: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "organizacja studencka",
      genitive: "organizacji studenckiej",
      dative: "organizacji studenckiej",
      accusative: "organizację studencką",
      instrumental: "organizacją studencką",
      locative: "organizacji studenckiej",
      vocative: "organizacjo studencka",
    },
    plural: {
      nominative: "organizacje studenckie",
      genitive: "organizacji studenckich",
      dative: "organizacjom studenckim",
      accusative: "organizacje studenckie",
      instrumental: "organizacjami studenckimi",
      locative: "organizacjach studenckich",
      vocative: "organizacje studenckie",
    },
  },
  [Resource.StudentOrganizationLinks]: REUSABLE_DECLENSIONS.link,
  [Resource.StudentOrganizationTags]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "tag",
      genitive: "tagu",
      dative: "tagowi",
      accusative: "tag",
      instrumental: "tagiem",
      locative: "tagu",
      vocative: "tagu",
    },
    plural: {
      nominative: "tagi",
      genitive: "tagów",
      dative: "tagom",
      accusative: "tagi",
      instrumental: "tagami",
      locative: "tagach",
      vocative: "tagi",
    },
  },
  [Resource.Majors]: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "kierunek",
      genitive: "kierunku",
      dative: "kierunkowi",
      accusative: "kierunek",
      instrumental: "kierunkiem",
      locative: "kierunku",
      vocative: "kierunku",
    },
    plural: {
      nominative: "kierunki",
      genitive: "kierunków",
      dative: "kierunkom",
      accusative: "kierunki",
      instrumental: "kierunkami",
      locative: "kierunkach",
      vocative: "kierunki",
    },
  },
  [Resource.Milestones]: {
    ...REUSABLE_DECLENSIONS.version,
    plural: {
      nominative: `wersje w ${QUOTED_ABOUT_US}`,
      genitive: `wersji w ${QUOTED_ABOUT_US}`,
      dative: `wersjom w ${QUOTED_ABOUT_US}`,
      accusative: `wersje w ${QUOTED_ABOUT_US}`,
      instrumental: `wersjami w ${QUOTED_ABOUT_US}`,
      locative: `wersjach w ${QUOTED_ABOUT_US}`,
      vocative: `wersje w ${QUOTED_ABOUT_US}`,
    },
  },
  [Resource.Versions]: {
    ...REUSABLE_DECLENSIONS.version,
    plural: {
      nominative: "wersje w dzienniku zmian",
      genitive: "wersji w dzienniku zmian",
      dative: "wersjom w dzienniku zmian",
      accusative: "wersje w dzienniku zmian",
      instrumental: "wersjami w dzienniku zmian",
      locative: "wersjach w dzienniku zmian",
      vocative: "wersje w dzienniku zmian",
    },
  },
  image: {
    gender: GrammaticalGender.Neuter,
    singular: {
      nominative: "zdjęcie",
      genitive: "zdjęcia",
      dative: "zdjęciu",
      accusative: "zdjęcie",
      instrumental: "zdjęciem",
      locative: "zdjęciu",
      vocative: "zdjęcie",
    },
    plural: {
      nominative: "zdjęcia",
      genitive: "zdjęć",
      dative: "zdjęciom",
      accusative: "zdjęcia",
      instrumental: "zdjęciami",
      locative: "zdjęciach",
      vocative: "zdjęcia",
    },
  },
  name: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "nazwa",
      genitive: "nazwy",
      dative: "nazwie",
      accusative: "nazwę",
      instrumental: "nazwą",
      locative: "nazwie",
      vocative: "nazwa",
    },
    plural: {
      nominative: "nazwy",
      genitive: "nazw",
      dative: "nazwom",
      accusative: "nazwy",
      instrumental: "nazwami",
      locative: "nazwach",
      vocative: "nazwy",
    },
  },
  title: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "tytuł",
      genitive: "tytułu",
      dative: "tytułowi",
      accusative: "tytuł",
      instrumental: "tytułem",
      locative: "tytule",
      vocative: "tytule",
    },
    plural: {
      nominative: "tytuły",
      genitive: "tytułów",
      dative: "tytułom",
      accusative: "tytuły",
      instrumental: "tytułami",
      locative: "tytułach",
      vocative: "tytuły",
    },
  },
  description: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "opis",
      genitive: "opisu",
      dative: "opisowi",
      accusative: "opis",
      instrumental: "opisem",
      locative: "opisie",
      vocative: "opisie",
    },
    plural: {
      nominative: "opisy",
      genitive: "opisów",
      dative: "opisy",
      accusative: "opisy",
      instrumental: "opisami",
      locative: "opisach",
      vocative: "opisy",
    },
  },
  shortDescription: REUSABLE_DECLENSIONS.shortDescription,
  shortDesc: REUSABLE_DECLENSIONS.shortDescription,
  id: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "identyfikator",
      genitive: "identyfikatora",
      dative: "identyfikatorowi",
      accusative: "identyfikator",
      instrumental: "identyfikatorem",
      locative: "identyfikatorze",
      vocative: "identyfikatorze",
    },
    plural: {
      nominative: "identyfikatory",
      genitive: "identyfikatorów",
      dative: "identyfikatorom",
      accusative: "identyfikatory",
      instrumental: "identyfikatorami",
      locative: "identyfikatorach",
      vocative: "identyfikatory",
    },
  },
  date: {
    gender: GrammaticalGender.Feminine,
    singular: {
      nominative: "data",
      genitive: "daty",
      dative: "dacie",
      accusative: "datę",
      instrumental: "datą",
      locative: "dacie",
      vocative: "dato",
    },
    plural: {
      nominative: "daty",
      genitive: "dat",
      dative: "datom",
      accusative: "daty",
      instrumental: "datami",
      locative: "datach",
      vocative: "daty",
    },
  },
  code: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "kod",
      genitive: "kodu",
      dative: "kodowi",
      accusative: "kod",
      instrumental: "kodem",
      locative: "kodzie",
      vocative: "kodzie",
    },
    plural: {
      nominative: "kody",
      genitive: "kodów",
      dative: "kodom",
      accusative: "kody",
      instrumental: "kodami",
      locative: "kodach",
      vocative: "kody",
    },
  },
  betterCode: {
    gender: GrammaticalGender.Masculine,
    singular: {
      nominative: "kod ze skrótem",
      genitive: "kodu ze skrótem",
      dative: "kodowi ze skrótem",
      accusative: "kod ze skrótem",
      instrumental: "kodem ze skrótem",
      locative: "kodzie ze skrótem",
      vocative: "kodzie ze skrótem",
    },
    plural: {
      nominative: "kody ze skrótem",
      genitive: "kodów ze skrótem",
      dative: "kodom ze skrótem",
      accusative: "kody ze skrótem",
      instrumental: "kodami ze skrótem",
      locative: "kodach ze skrótem",
      vocative: "kody ze skrótem",
    },
  },
} satisfies RecordIntersection<
  Resource,
  string,
  Pluralized<Declensions> & DeclensionData
>;

/** Noun phrase mappings that inflect like their base noun with genitive transformations (e.g. 'data' → 'data utworzenia'). */
export const NOUN_PHRASE_TRANSFORMATIONS = {
  createdAt: {
    base: "date",
    transform: (base) => `${base} utworzenia`,
  },
  updatedAt: {
    base: "date",
    transform: (base) => `${base} aktualizacji`,
  },
} satisfies Record<
  string,
  { base: DeclinableSimpleNoun; transform: (base: string) => string }
>;

/** A static dictionary of declensions for determiners in the Polish language. */
export const DETERMINER_DECLENSIONS = {
  this: {
    [GrammaticalGender.Masculine]: {
      singular: {
        nominative: "ten",
        genitive: "tego",
        dative: "temu",
        accusative: "ten",
        instrumental: "tym",
        locative: "tym",
        vocative: "ten",
      },
      plural: {
        nominative: "ci",
        genitive: "tych",
        dative: "tym",
        accusative: "tych",
        instrumental: "tymi",
        locative: "tych",
        vocative: "ci",
      },
    },
    [GrammaticalGender.Feminine]: {
      singular: {
        nominative: "ta",
        genitive: "tej",
        dative: "tej",
        accusative: "tę",
        instrumental: "tą",
        locative: "tej",
        vocative: "ta",
      },
      plural: {
        nominative: "te",
        genitive: "tych",
        dative: "tym",
        accusative: "te",
        instrumental: "tymi",
        locative: "tych",
        vocative: "te",
      },
    },
    [GrammaticalGender.Neuter]: {
      singular: {
        nominative: "to",
        genitive: "tego",
        dative: "temu",
        accusative: "to",
        instrumental: "tym",
        locative: "tym",
        vocative: "to",
      },
      plural: {
        nominative: "te",
        genitive: "tych",
        dative: "tym",
        accusative: "te",
        instrumental: "tymi",
        locative: "tych",
        vocative: "te",
      },
    },
  },
  new: {
    [GrammaticalGender.Masculine]: {
      singular: {
        nominative: "nowy",
        genitive: "nowego",
        dative: "nowemu",
        accusative: "nowy",
        instrumental: "nowym",
        locative: "nowym",
        vocative: "nowy",
      },
      plural: {
        nominative: "nowi",
        genitive: "nowych",
        dative: "nowym",
        accusative: "nowych",
        instrumental: "nowymi",
        locative: "nowych",
        vocative: "nowi",
      },
    },
    [GrammaticalGender.Feminine]: {
      singular: {
        nominative: "nowa",
        genitive: "nowej",
        dative: "nowej",
        accusative: "nową",
        instrumental: "nową",
        locative: "nowej",
        vocative: "nowa",
      },
      plural: {
        nominative: "nowe",
        genitive: "nowych",
        dative: "nowym",
        accusative: "nowe",
        instrumental: "nowymi",
        locative: "nowych",
        vocative: "nowe",
      },
    },
    [GrammaticalGender.Neuter]: {
      singular: {
        nominative: "nowe",
        genitive: "nowego",
        dative: "nowemu",
        accusative: "nowe",
        instrumental: "nowym",
        locative: "nowym",
        vocative: "nowe",
      },
      plural: {
        nominative: "nowe",
        genitive: "nowych",
        dative: "nowym",
        accusative: "nowe",
        instrumental: "nowymi",
        locative: "nowych",
        vocative: "nowe",
      },
    },
  },
  existing: {
    [GrammaticalGender.Masculine]: {
      singular: {
        nominative: "istniejący",
        genitive: "istniejącego",
        dative: "istniejącemu",
        accusative: "istniejący",
        instrumental: "istniejącym",
        locative: "istniejącym",
        vocative: "istniejący",
      },
      plural: {
        nominative: "istniejący",
        genitive: "istniejących",
        dative: "istniejącym",
        accusative: "istniejących",
        instrumental: "istniejącymi",
        locative: "istniejących",
        vocative: "istniejący",
      },
    },
    [GrammaticalGender.Feminine]: {
      singular: {
        nominative: "istniejąca",
        genitive: "istniejącej",
        dative: "istniejącej",
        accusative: "istniejącą",
        instrumental: "istniejącą",
        locative: "istniejącej",
        vocative: "istniejąca",
      },
      plural: {
        nominative: "istniejące",
        genitive: "istniejących",
        dative: "istniejącym",
        accusative: "istniejące",
        instrumental: "istniejącymi",
        locative: "istniejących",
        vocative: "istniejące",
      },
    },
    [GrammaticalGender.Neuter]: {
      singular: {
        nominative: "istniejące",
        genitive: "istniejącego",
        dative: "istniejącemu",
        accusative: "istniejące",
        instrumental: "istniejącym",
        locative: "istniejącym",
        vocative: "istniejące",
      },
      plural: {
        nominative: "istniejące",
        genitive: "istniejących",
        dative: "istniejącym",
        accusative: "istniejące",
        instrumental: "istniejącymi",
        locative: "istniejących",
        vocative: "istniejące",
      },
    },
  },
} satisfies Record<string, Record<GrammaticalGender, Pluralized<Declensions>>>;
