name: "Install"
description: "Sets up Node, and installs dependencies"
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"

    - name: Install dependencies
      shell: bash
      run: npm ci
