name: Check Coverage Regression

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.test.ts"
      - "**/*.test.tsx"
      - "tests/**"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Save current branch coverage
        run: cp coverage/coverage-summary.json current-coverage.json

      - name: Checkout base branch
        run: |
          git fetch origin main
          git checkout origin/main

      - name: Install dependencies on base branch
        run: npm ci

      - name: Run tests on base branch
        run: npm run test:coverage

      - name: Save base branch coverage
        run: cp coverage/coverage-summary.json base-coverage.json

      - name: Compare coverage
        run: node .github/scripts/check-coverage-diff.js

      - name: Return to previous branch
        run: git checkout -
        if: always()
